global:
    scrape_interval: 60s
    evaluation_interval: 60s

rule_files: []

scrape_configs:
    - job_name: autodelete
      static_configs:
        - targets: ["127.0.0.4:6132"]
          labels: {"shard": "2"}
        - targets: ["127.0.0.4:6133"]
          labels: {"shard": "3"}
        - targets: ["127.0.0.4:6134"]
          labels: {"shard": "4"}
        - targets: ["127.0.0.4:6148"]
          labels: {"shard": "18"}
        - targets: ["127.0.0.4:6149"]
          labels: {"shard": "19"}
        - targets: ["127.0.0.4:6150"]
          labels: {"shard": "20"}

