global:
    scrape_interval: 60s
    evaluation_interval: 60s

rule_files: []

scrape_configs:
    - job_name: autodelete
      static_configs:
        - targets: ["127.0.0.4:6130"]
          labels: {"shard": "0"}
        - targets: ["127.0.0.4:6131"]
          labels: {"shard": "1"}
        - targets: ["127.0.0.4:6146"]
          labels: {"shard": "16"}
        - targets: ["127.0.0.4:6147"]
          labels: {"shard": "17"}

