global:
    scrape_interval: 60s
    evaluation_interval: 60s

rule_files: []

scrape_configs:
    - job_name: aggregate
      honor_labels: true
      metrics_path: '/federate'
      params:
          'match[]':
              - '{job="autodelete"}'
      static_configs:
        - targets: ["127.0.0.1:4001", "127.0.0.1:4002", "127.0.0.1:4003", "127.0.0.1:4004", "127.0.0.1:4005"]

